name: build

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Duser.language=uk -Duser.country=UA"

    steps:
      - name: Checkout Project Sources
        uses: actions/checkout@v4.2.2

      - name: Set Up JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn license:format clean install 
